name = "heron"
version = "0.1.0"
defaultTargets = ["Heron"]

[[lean_lib]]
name = "Heron"
globs = ["Heron.*"]

[[lean_lib]]
name = "Demo"
globs = ["Demo"]

[[lean_exe]]
name = "dump-ast"
root = "DumpAst"
