/-
Registry for implicit import dependencies that cannot be recorded via
`Lean.recordExtraModUse` during linter execution, because
`Lean.Elab.Command.runLinters` rolls back env changes between linters.

Kept as a separate `module` so both `Heron.Rule` (non-module, where the
registry is populated from linter bodies) and `Heron.ImportAnalysis`
(module, where it is consumed) can depend on it.
-/
module

public import Lean.Data.Name
public import Std.Data.HashMap
public import Std.Data.HashSet

public section

namespace Heron

open Lean

/-- Source module of each registered rule, keyed by rule name.
Populated at import time by an `@[init]` aux decl generated by
`handleRuleAttribute` — see `Heron.Rule`. -/
initialize ruleSourceModules : IO.Ref (Std.HashMap Name Name) ←
  IO.mkRef { }

/-- Per-file record of rule source modules whose linter fired, keyed by
the file's main module name. Consumed by `Heron.ImportAnalysis` alongside
`Lean.getExtraModUsesInEnv` to detect implicit dependencies. -/
initialize ruleUsedInFiles : IO.Ref (Std.HashMap Name (Std.HashSet Name)) ←
  IO.mkRef { }

end Heron
