-- Checks
import Heron.Check.RflToExactRfl
import Heron.Check.MergeIntros
import Heron.Check.UnnecessaryIdRun
import Heron.Check.UnnecessaryMut
import Heron.Check.BoolMatchToIf
import Heron.Check.DuplicateAltToOrPattern
import Heron.Check.MergeBinders
import Heron.Check.NestedMonadToJoin
import Heron.Check.NestedMonadToTransformer
import Heron.Check.RedundantLetWildcard
import Heron.Check.TupleMatchToSimultaneous
import Heron.Check.MatchToIfLet
import Heron.Check.GetSetToModify
import Heron.Check.RedundantElsePureUnit
import Heron.Check.IfNotToUnless
import Heron.Check.NatLiteralPatterns
import Heron.Check.FunMatchToMatchFun
import Heron.Check.ExprAppChainToMkAppN
import Heron.Check.FunToCdot
-- Refactors
import Heron.Refactor.FlipIf
import Heron.Refactor.Inline
import Heron.Refactor.BindToDo
